version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    groups:
      ndarray-packages:
        patterns:
          - "ndarray*"
