[package]
name = "crispr_screen"
version = "0.1.14"
edition = "2021"
description = "A fast and configurable differential expression analysis tool for CRISPR screens"
license = "MIT"
documentation = "https://docs.rs/crispr_screen"
repository = "https://github.com/noamteyssier/crispr_screen"
homepage = "https://noamteyssier.github.io/crispr_screen/"
keywords = ["cli", "CRISPR", "bioinformatics", "degs", "sgRNA"]
categories = ["command-line-utilities", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adjustp = "0.1.1"
alpha-rra = "0.1.5"
anyhow = "1.0.59"
clap = { version = "4.1.1", features = ["derive"] }
colored = "2.0.0"
csv = "1.1.6"
hashbrown = "0.12.3"
intc = "0.1.4"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
ndarray-stats = "0.5.0"
noisy_float = "0.2.0"
rayon = "1.5.3"
statrs = "0.16.0"
thiserror = "1.0.38"
