[package]
name = "crispr_screen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adjustp = "0.1.1"
anyhow = "1.0.59"
clap = { version = "4.1.1", features = ["derive"] }
colored = "2.0.0"
hashbrown = "0.12.3"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
ndarray-stats = "0.5.0"
noisy_float = "0.2.0"
polars = { version = "0.26.1", features = ["ndarray"] }
rayon = "1.5.3"
statrs = "0.15.0"
thiserror = "1.0.38"
